### ISSUE TITLE
Autogenerated spec tests don't work for certain factsets

### ISSUE THREAD

**Issue by TraGicCode** [dylanratcliffe/onceover#105] opened 2017-07-30 04:36 UTC
When running onceover run spec the autogenerated tests to ensure my classes compile without any dependency cycles don't work for certain factsets.

Windows_Server-2012r2-64
solaris-10_u9-sparc-64
AIX-6.1-powerpc

Error message on the failed tests are

 error during compilation: Evaluation Error: Error while evaluating a Function Call, Could not find class ::role::webserver for .localdomain at line 2:1 on node .localdomain

![image](https://user-images.githubusercontent.com/6224270/28750654-88582d10-74b6-11e7-8b27-9c3ae0619042.png)

**Comment by dylanratcliffe** [comment] 2017-07-31 03:42
Hmm, that's a strange one... Is your `role::webserver` class actually designed to work on all those operating systems? I would be reducing the scope to only cover the OSes on which  is supposed to work and then seeing if we get an error. It's not really expected that the test runs will pass first time unless you have **very** versatile code.

**Comment by TraGicCode** [comment] 2017-07-31 03:45
This was just a test control repo for playing with onceover.  It literally only has a class called role::webserver that only contains an include of a profile::base class which is empty



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by TraGicCode** [comment] 2017-08-11 23:50
@dylanratcliffe Any update on this

**Comment by dylanratcliffe** [comment] 2017-08-14 22:42
Can you link me to the repo so I can try it out?

**Comment by TraGicCode** [comment] 2017-08-22 12:00
Going to try and reproduce this now.  I think this might have been related to an older version of rspec-puppet.  I will get back to you soon

**Comment by TraGicCode** [comment] 2017-08-22 12:19
Updated to the lastest and now they all fail.  Looks like the site directory i have is not getting moved to the modulepath in the .onceover directory.

https://github.com/TraGicCode/once-over-testing

**Comment by dylanratcliffe** [comment] 2017-08-24 01:29
Okay so if I try that code it works perfectly. I have a suspicion it will be to do with the weird caching that's going on. There is a larger project that's been created to improve the way onceover manages the `.onceover` directory which hopefully will fix this, but yeah, still can't reproduce

**Comment by dylanratcliffe** [comment] 2018-01-16 00:02
This has likely been fixed as part of v3.3.2, as I could not reproduce I'm closing this

**Closed by dylanratcliffe** 2018-01-16 00:02 UTC
Labels: bug
