### ISSUE TITLE
Puppet fails to validate valid Windows paths running on Linux

### ISSUE THREAD

**Issue by sandymcp** [dylanratcliffe/onceover#109] opened 2017-08-03 07:32 UTC
Running onceover on a Linux box I get problems with the roles in our control-repo which are handling windows components and their 'should compile' tests which are running against a windows factset. It is not a onceover issue as such, but an underlying rspec/puppet issue which is related to [https://github.com/rodjek/rspec-puppet/issues/192](https://github.com/rodjek/rspec-puppet/issues/192). 

I tried the recommended solution there, but it didn't help me much, my valid unix paths for puppet master actions got rejected as it then tests only against windows. 

It is possible to workaround this by monkey patching the Puppet::Util::absolute_file? to take notice of the kernel set in the factset and if the kernel in the factset is different to the actual platform check the path against the facts[:kernel]. To make this work I had to patch the onceover templates: the spec_helper.rb.erb to require the patch and test_spec.rb.erb to add the fact set as a thread local so that the patch can get at the facts. I was therefore wondering if there is general interest in being able to add monkey patches? 

These files were branched off v3.2.0 (simplified change to spec_helper template)

$ git diff v3.2.0 templates/spec_helper.rb.erb
```
diff --git a/templates/spec_helper.rb.erb b/templates/spec_helper.rb.erb
index 3981197..3af602b 100644
--- a/templates/spec_helper.rb.erb
+++ b/templates/spec_helper.rb.erb
@@ -15,3 +15,6 @@ RSpec.configure do |c|
   c.manifest = '<%= repo.temp_manifest %>'
   ENV['STRICT_VARIABLES'] = '<%= self.strict_variables %>'
 end
+
+Dir[File.dirname(__FILE__) + '/onceover_helper.rb'].each {|file| require file }
+
```

$ git diff v3.2.0 templates/test_spec.rb.erb
```
diff --git a/templates/test_spec.rb.erb b/templates/test_spec.rb.erb
index 61ba5fe..32c8da8 100644
--- a/templates/test_spec.rb.erb
+++ b/templates/test_spec.rb.erb
@@ -28,7 +28,10 @@ $onceover_node = '<%= node.name %>'
 END
     }
 <% end -%>
-    it { should compile }
+    it {
+      Thread.current[:facts] = <%= node.fact_set %>
+        should compile
+    }
   end
 <% end -%>
 end
```
monkey_patches/absolute_file?
```
module Puppet
    module Util
        def self.absolute_path?(path, platform=nil)
            platform ||= Puppet::Util::Platform.windows? ? :windows : :posix
            regex = case platform
                        when :windows
                            AbsolutePathWindows
                        when :posix
                            AbsolutePathPosix
                        else
                            raise Puppet::DevError, "unknown platform #{platform} in absolute_path"
                    end
            regex
            match = !!(path =~ regex)
            unless match
                facts = Thread.current[:facts]
                unless facts == nil
                    kernel = facts['kernel']
                    unless kernel == nil
                        test_platform = nil
                        case kernel.downcase
                          when 'windows'
                             test_platform = :windows
                          when 'linux'
                             test_platform = :posix
                        end
                        unless test_platform == platform
                            match = absolute_path?(path, test_platform)
                        end
                    end
                end
            end
            match
        end
    end
end
```

**Comment by jessereynolds** [comment] 2017-08-09 02:37
We definitely need a workaround here, and if a monkey patch is the only way to do it for now then lets go the monkey patch route. @dylanratcliffe would you accept a PR to allow monkey patching like this?

**Comment by jessereynolds** [comment] 2017-08-09 02:40
Duplicate of #59

**Comment by jessereynolds** [comment] 2017-08-09 06:05
@sandymcp rspec-puppet already monkey patches Puppet::Util.absolute_path? if the fact operatingsystem and osfamily are set to "windows", so this shouldn't be necessary with current rspec-puppet. I've validated this with rspec-puppet 2.6.7. 

Note that some modules, eg older versions of puppetlabs/inifile, do not use Puppet::Util.absolute_path? and instead implement their own logic. In my case I was getting the absolute path error with latest rspec-puppet but an older inifile module, upgrading inifile to 2.0.0 fixed this issue with onceover for me.

**Comment by sandymcp** [comment] 2017-08-09 07:48
@jessereynolds thanks for the info, very useful. However, we're still using 2.5.0 and Puppet 4.7.0 and I had issues with the latest onceover [#108](https://github.com/dylanratcliffe/onceover/issues/108). 

I'm trying to get onceover running on an existing very large control-repo, retro-fit rspec tests, etc. and I don't really want to anything until I have my tests in place and can start making changes safely. I'll run with my own patch until I can achieve stability, then look at upgrading puppet, rspec, onceover and anything else I can think of.

BTW, I also simplified my patch to the spec_helper template to optionally include a onceover_helper, this was because I found out I wanted to do more rspec configuration than the existing template does (code coverage, formatting, etc. I've edited my original post accordingly.

**Comment by dylanratcliffe** [comment] 2018-01-16 00:15
If this is fixed upstream in rspec-puppet then I'll close this

**Closed by dylanratcliffe** 2018-01-16 00:15 UTC

**Comment by jessereynolds** [comment] 2018-02-28 12:12
Note to future self (and others): rspec-puppet looks at the 'operatingsystem' fact to determine if it should pretend to be running on that OS instead of the actual OS. Eg, you need to have operatingsystem = windows in your Windows factsets in order to get the rspec-puppet monekypatching OS pretenting goodness.
